// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// countBitsFromRaw
int countBitsFromRaw(RawVector rv);
RcppExport SEXP binaryDist_countBitsFromRaw(SEXP rvSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawVector >::type rv(rvSEXP);
    __result = Rcpp::wrap(countBitsFromRaw(rv));
    return __result;
END_RCPP
}
// bDist
NumericVector bDist(RawMatrix mat);
RcppExport SEXP binaryDist_bDist(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< RawMatrix >::type mat(matSEXP);
    __result = Rcpp::wrap(bDist(mat));
    return __result;
END_RCPP
}
