# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

countBitsFromRaw <- function(rv) {
    .Call('binaryDist_countBitsFromRaw', PACKAGE = 'binaryDist', rv)
}

bDist <- function(mat) {
    .Call('binaryDist_bDist', PACKAGE = 'binaryDist', mat)
}

